scrape_configs:
  - job_name: 'flask-app'
    static_configs:
      - targets: ['flask-app:5000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # - job_name: 'prometheus'
  #   static_configs:
  #     - targets: ['prometheus:9090']
